### ISSUE TITLE
Compatibilty with Flutter master branch

### ISSUE THREAD

**Issue by Solido** [holyspidoo/PubSpecCheck#1]
Because pub_client >=2.0.0 depends on http ^0.11.3+17 and flutter_calender depends on http ^0.12.0, pub_client >=2.0.0 is forbidden.
So, because flutter_calender depends on pub_client ^3.0.0, version solving failed.

pub get failed (1)

Moved to pub_client: ^3.0.2

**Comment by holyspidoo** [comment]
I'm sorry, I don't quite get the issue. How should I go about reproducing the problem?

**Comment by Solido** [comment]
You can find this problem when integrating your script directly inside a Flutter project using the default Flutter dart cmd.

**Comment by holyspidoo** [comment]
I see! I would not recommend adding this to a Flutter project though (at least I never thought about it), it is meant to be a simple standalone script/app. But in your flutter project directory, you can run this script via terminal to inspect the yaml file. 

example:
```
> location_of_dart/dart location_of_SpecCheck/SpecCheck.dart pubspec.yaml
```

Me personnaly, I created an alias in my shell to map `location_of_dart/dart location_of_SpecCheck/SpecCheck.dart` to `spec`, so all I do in any flutter or Dart directory:

```
> spec pubspec.yaml
```

And if Dart is installed (not flutter but actual Dart), `location_of_dart` is never needed.

**Comment by Solido** [comment]
Thanks ! I'm just tinkering with your code to integrate it as simple dev dependency for Flutter.
